global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: api-server
    static_configs:
      - targets: ["sample-api:8001"]
  - job_name: payment-service
    static_configs:
      - targets: ["sample-payment:8002"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
